### ISSUE TITLE
The demo isn't work

### ISSUE THREAD

**Issue by wuyuzaizai** [DetectionTeamUCAS/Models#1]
FasterRCNN_20180515_DOTA_v3 part1-part4 did not work for demo @yangxue0827

**Comment by yangxue0827** [comment]
Could you please provide more detailed information, so that I can find where is wrong.

**Comment by wuyuzaizai** [comment]
I just pick images from train and test folders, and using the trained model , but none of objects can be  detected. @yangxue0827

**Comment by yangxue0827** [comment]
Folder format of trained weights 
```
output
     |-trained_weights 
           |-FasterRCNN_20180515_DOTA_v3
                  |-checkpoint
                  |-voc_108001model.ckpt.index
                  |-voc_108001model.ckpt.meta
                  |-voc_108001model.ckpt.data-0000-of-00001
```

**Comment by wuyuzaizai** [comment]
it's work! thx @yangxue0827
