### ISSUE TITLE
Where is the Cascade-RCNN_Tensorflow file?

### ISSUE THREAD

**Issue by handsomefengfeng** [DetectionTeamUCAS/Models#11]
I'm reading the github"Cascade-RCNN_Tensorflow"
It required the trained model in https://github.com/DetectionTeamUCAS/Models/tree/master/Cascade-RCNN_Tensorflow
How can i obtain it?

**Comment by yangxue0827** [comment]
if you have a baidu drive account, you can download from [Baidu Drive](https://pan.baidu.com/s/1m36qbJaB728FR3UtUWpOww), password:2u6o.
