### ISSUE TITLE
权重文件能不能上传到百度然后给个分享呀，github下载太痛苦。。。

### ISSUE THREAD

**Issue by kevin0525** [DetectionTeamUCAS/Models#12]

**Comment by yangxue0827** [comment]
我现在的模型都是上传百度盘了，以前的没办法了 @kevin0525

**Comment by kevin0525** [comment]
@yangxue0827  请问下能够给下已上传的模型百度云盘链接么，或者是如果方便的话可以发邮件给我么。759424614@qq.com，十分感谢。
