### ISSUE TITLE
Do you have R2CNN-Plus-Plus_Tensorflow model outside baidu? 

### ISSUE THREAD

**Issue by alison-carrera** [DetectionTeamUCAS/Models#13]
Hello, thanks for this nice algorithm! I'm from Brazil, but I can't download it from here. Could you host this file in another kind of provider? Thanks!

**Comment by yangxue0827** [comment]
[google drive link](https://drive.google.com/open?id=1gkMdXe5NoN0_8_H1FFTh-p2sAvqmF1UB)  @alison-carrera

**Comment by alison-carrera** [comment]
Thanks @yangxue0827 !
