### ISSUE TITLE
我只想说这个models我下载了一天也没下载成功。各种方法都用了，下载下来的压缩包解压一直显示有错误

### ISSUE THREAD

**Issue by cmstudyscode** [DetectionTeamUCAS/Models#15]
有成功下载下来的小伙伴可以百度云或者别的方法分享一下么。FPN_Res101_20181201.part1.rar

**Comment by yangxue0827** [comment]
[Baidu Drive](https://pan.baidu.com/s/1m36qbJaB728FR3UtUWpOww), password:2u6o.
完整下载后，建议在windows下解压，因为是分卷压缩的，windows解压操作简单（右键解压就可以），linux的话就比较麻烦。 @cmstudyscode

**Comment by tangyuqing123** [comment]
> 有成功下载下来的小伙伴可以百度云或者别的方法分享一下么。FPN_Res101_2
你成功了吗，如果有的话发我一份数据吧，1551869307@qq.com,十分感谢
