### ISSUE TITLE
The model can't be unzip, part of the model are missing. 

### ISSUE THREAD

**Issue by Yansslc** [DetectionTeamUCAS/Models#6]
I'm trying to download the model for R2CNN-FasterRCNN, but the downloaded compressed file of trained model(including 4 part of them) seems to miss the part5, so the compressed file can't be unzip. Can you check the compressed file please?  Or can you tell me the right way to unzip it? Thank you for help me! 
(the model I downloaded is as shown in the picture)
 
![微信图片_20190514111851](https://user-images.githubusercontent.com/42287555/57668493-1ab8a500-763a-11e9-984c-888c2c8c159a.png)

**Comment by yangxue0827** [comment]
You may have used the wrong command and it is recommended to extract it on windows. @Yansslc
